x=input()
y=x.split(" ")
y.pop (len(y)-1)
y.append(0)
y.append(0)
y.append(0)
y.append(0)
y.append(0)
y.append(0)
dp=[0]*(len(y))
dp[0]=int(y[0])
dp[1]=int(y[1])
dp[2]=int(dp[0])+int(y[2])
dp[3]=max(int(dp[0]),int(dp[1]))+int(y[3])
for i in range(4,len (y)):
    dp[i]=max (int(dp[i-2]), int(dp[i-3]))+int(y[i])
print (max (dp)) 
